INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES('1', 'lukasz', 'password');

INSERT INTO NOTES(ID, USER_ID, NOTE) VALUES('1', '1', 'note');

INSERT INTO TAGS(ID, USER_ID, TAG) VALUES('1', '1', 'tag');

INSERT INTO NOTES_TAGS(NOTE_ID, TAG_ID) VALUES('1', '1');